version: '3.9'
services:
  db:
    container_name: inmana_db
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: inmana
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306

  app:
    container_name: inmana
    image: hyperf/hyperf:7.4-alpine-v3.11-swoole
    entrypoint: /bin/sh
    working_dir: /app
    environment:
      TIMEZONE: America/Sao_Paulo
    env_file:
      - .env
    volumes:
      - ./:/app
    ports:
      - 9501:9501
    links:
      - db